"""initial schema

Revision ID: eaae242b764c
Revises: 
Create Date: 2026-08-21 14:09:00.774083
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'eaae242b764c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_calls',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_schema', sa.String(length=120), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_calls'))
    )
    with op.batch_alter_table('agent_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_calls_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_calls_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_calls_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('datasets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('name', name=op.f('uq_datasets_name'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_slug'), ['slug'], unique=True)

    op.create_table('embeddings',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'model', name='uq_embedding_entity_model')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_entity_type'), ['entity_type'], unique=False)

    op.create_table('methods',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methods')),
    sa.UniqueConstraint('name', name=op.f('uq_methods_name'))
    )
    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_methods_slug'), ['slug'], unique=True)

    op.create_table('papers',
    sa.Column('doi', sa.String(length=120), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title_hash', sa.String(length=64), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=400), nullable=True),
    sa.Column('source_provider', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers'))
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_normalized_title_hash'), ['normalized_title_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_publication_year'), ['publication_year'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('topics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('name', name=op.f('uq_topics_name'))
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('paper_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_paper_datasets_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_datasets_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_datasets')),
    sa.UniqueConstraint('paper_id', 'dataset_id', name='uq_paper_dataset')
    )
    with op.batch_alter_table('paper_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_datasets_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_datasets_paper_id'), ['paper_id'], unique=False)

    op.create_table('paper_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('method_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], name=op.f('fk_paper_methods_method_id_methods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_methods_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_methods')),
    sa.UniqueConstraint('paper_id', 'method_id', name='uq_paper_method')
    )
    with op.batch_alter_table('paper_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_methods_method_id'), ['method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_methods_paper_id'), ['paper_id'], unique=False)

    op.create_table('paper_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_topics_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_paper_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_topics')),
    sa.UniqueConstraint('paper_id', 'topic_id', name='uq_paper_topic')
    )
    with op.batch_alter_table('paper_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_topics_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_topics_topic_id'), ['topic_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discovery_mode', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspaces_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_user_id'), ['user_id'], unique=False)

    op.create_table('evidence',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('source_title', sa.String(length=600), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_evidence_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_evidence_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('generated_reports',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_generated_reports_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_reports'))
    )
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_reports_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('research_jobs',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=80), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_research_jobs_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_jobs'))
    )
    with op.batch_alter_table('research_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('researchers',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('affiliation', sa.String(length=300), nullable=True),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_researchers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_researchers'))
    )
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researchers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_researchers_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], name=op.f('fk_job_events_job_id_research_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    op.create_table('paper_authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('researcher_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_authors_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], name=op.f('fk_paper_authors_researcher_id_researchers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_authors'))
    )
    with op.batch_alter_table('paper_authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_authors_paper_id'), ['paper_id'], unique=False)

    op.create_table('research_gaps',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gap_type', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], name=op.f('fk_research_gaps_job_id_research_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_gaps_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_gaps'))
    )
    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_gaps_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('research_profiles',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('researcher_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], name=op.f('fk_research_profiles_researcher_id_researchers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_profiles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_profiles'))
    )
    with op.batch_alter_table('research_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_profiles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('research_trajectories',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('researcher_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('trajectory_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], name=op.f('fk_research_trajectories_researcher_id_researchers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_trajectories_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_trajectories')),
    sa.UniqueConstraint('workspace_id', 'researcher_id', name='uq_traj_ws_researcher')
    )
    with op.batch_alter_table('research_trajectories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_trajectories_researcher_id'), ['researcher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_trajectories_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('researcher_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('researcher_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], name=op.f('fk_researcher_aliases_researcher_id_researchers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_researcher_aliases'))
    )
    with op.batch_alter_table('researcher_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researcher_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_researcher_aliases_researcher_id'), ['researcher_id'], unique=False)

    op.create_table('documents',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['research_profiles.id'], name=op.f('fk_documents_profile_id_research_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_documents_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('research_gap_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gap_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_research_gap_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gap_id'], ['research_gaps.id'], name=op.f('fk_research_gap_evidence_gap_id_research_gaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_gap_evidence'))
    )
    with op.batch_alter_table('research_gap_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_gap_evidence_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_gap_evidence_gap_id'), ['gap_id'], unique=False)

    op.create_table('research_intersections',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('shared_problem', sa.Text(), nullable=True),
    sa.Column('complementary_expertise', sa.Text(), nullable=True),
    sa.Column('research_gap_id', sa.String(length=36), nullable=True),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('researcher_a_id', sa.String(length=36), nullable=False),
    sa.Column('researcher_b_id', sa.String(length=36), nullable=False),
    sa.Column('why_researcher_a', sa.Text(), nullable=True),
    sa.Column('why_researcher_b', sa.Text(), nullable=True),
    sa.Column('novelty_confidence', sa.Float(), nullable=False),
    sa.Column('feasibility_confidence', sa.Float(), nullable=False),
    sa.Column('discovery_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], name=op.f('fk_research_intersections_job_id_research_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_gap_id'], ['research_gaps.id'], name=op.f('fk_research_intersections_research_gap_id_research_gaps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['researcher_a_id'], ['researchers.id'], name=op.f('fk_research_intersections_researcher_a_id_researchers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_b_id'], ['researchers.id'], name=op.f('fk_research_intersections_researcher_b_id_researchers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_intersections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_intersections'))
    )
    with op.batch_alter_table('research_intersections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_intersections_researcher_a_id'), ['researcher_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_intersections_researcher_b_id'), ['researcher_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_intersections_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('research_profile_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dna_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['research_profiles.id'], name=op.f('fk_research_profile_versions_profile_id_research_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_profile_versions')),
    sa.UniqueConstraint('profile_id', 'version', name='uq_profile_version')
    )
    with op.batch_alter_table('research_profile_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_profile_versions_profile_id'), ['profile_id'], unique=False)

    op.create_table('collaboration_candidates',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=True),
    sa.Column('researcher_a_id', sa.String(length=36), nullable=False),
    sa.Column('researcher_b_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['research_intersections.id'], name=op.f('fk_collaboration_candidates_intersection_id_research_intersections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['researcher_a_id'], ['researchers.id'], name=op.f('fk_collaboration_candidates_researcher_a_id_researchers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_b_id'], ['researchers.id'], name=op.f('fk_collaboration_candidates_researcher_b_id_researchers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_collaboration_candidates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaboration_candidates'))
    )
    with op.batch_alter_table('collaboration_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaboration_candidates_researcher_a_id'), ['researcher_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_candidates_researcher_b_id'), ['researcher_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_candidates_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('hypotheses',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('hypothesis_text', sa.Text(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('dataset', sa.Text(), nullable=True),
    sa.Column('baseline', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('expected_contribution', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['research_intersections.id'], name=op.f('fk_hypotheses_intersection_id_research_intersections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_hypotheses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses'))
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_intersection_id'), ['intersection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('intersection_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_intersection_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intersection_id'], ['research_intersections.id'], name=op.f('fk_intersection_evidence_intersection_id_research_intersections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intersection_evidence'))
    )
    with op.batch_alter_table('intersection_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intersection_evidence_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intersection_evidence_intersection_id'), ['intersection_id'], unique=False)

    op.create_table('experiments',
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('baseline', sa.Text(), nullable=True),
    sa.Column('proposed_approach', sa.Text(), nullable=True),
    sa.Column('dataset', sa.Text(), nullable=True),
    sa.Column('dataset_status', sa.String(length=20), nullable=False),
    sa.Column('training_setup', sa.Text(), nullable=True),
    sa.Column('evaluation_setup', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('ablations', sa.JSON(), nullable=False),
    sa.Column('expected_outcomes', sa.Text(), nullable=True),
    sa.Column('failure_conditions', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], name=op.f('fk_experiments_hypothesis_id_hypotheses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_hypothesis_id'), ['hypothesis_id'], unique=True)

    # ### end Alembic commands ###

    # SQLite FTS5 index for paper search (graceful if unavailable)
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS papers_fts USING fts5("
        "paper_id UNINDEXED, title, abstract)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS papers_fts")
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_hypothesis_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('intersection_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intersection_evidence_intersection_id'))
        batch_op.drop_index(batch_op.f('ix_intersection_evidence_evidence_id'))

    op.drop_table('intersection_evidence')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_intersection_id'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('collaboration_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaboration_candidates_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_candidates_researcher_b_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_candidates_researcher_a_id'))

    op.drop_table('collaboration_candidates')
    with op.batch_alter_table('research_profile_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_profile_versions_profile_id'))

    op.drop_table('research_profile_versions')
    with op.batch_alter_table('research_intersections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_intersections_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_research_intersections_researcher_b_id'))
        batch_op.drop_index(batch_op.f('ix_research_intersections_researcher_a_id'))

    op.drop_table('research_intersections')
    with op.batch_alter_table('research_gap_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_gap_evidence_gap_id'))
        batch_op.drop_index(batch_op.f('ix_research_gap_evidence_evidence_id'))

    op.drop_table('research_gap_evidence')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    with op.batch_alter_table('researcher_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researcher_aliases_researcher_id'))
        batch_op.drop_index(batch_op.f('ix_researcher_aliases_alias'))

    op.drop_table('researcher_aliases')
    with op.batch_alter_table('research_trajectories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_trajectories_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_research_trajectories_researcher_id'))

    op.drop_table('research_trajectories')
    with op.batch_alter_table('research_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_profiles_workspace_id'))

    op.drop_table('research_profiles')
    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_gaps_workspace_id'))

    op.drop_table('research_gaps')
    with op.batch_alter_table('paper_authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_authors_paper_id'))

    op.drop_table('paper_authors')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('researchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researchers_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_researchers_name'))

    op.drop_table('researchers')
    with op.batch_alter_table('research_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_research_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_jobs_status'))

    op.drop_table('research_jobs')
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_workspace_id'))

    op.drop_table('generated_reports')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_paper_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_user_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('paper_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_topics_topic_id'))
        batch_op.drop_index(batch_op.f('ix_paper_topics_paper_id'))

    op.drop_table('paper_topics')
    with op.batch_alter_table('paper_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_methods_paper_id'))
        batch_op.drop_index(batch_op.f('ix_paper_methods_method_id'))

    op.drop_table('paper_methods')
    with op.batch_alter_table('paper_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_datasets_paper_id'))
        batch_op.drop_index(batch_op.f('ix_paper_datasets_dataset_id'))

    op.drop_table('paper_datasets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))

    op.drop_table('topics')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_publication_year'))
        batch_op.drop_index(batch_op.f('ix_papers_provider_id'))
        batch_op.drop_index(batch_op.f('ix_papers_normalized_title_hash'))
        batch_op.drop_index(batch_op.f('ix_papers_doi'))

    op.drop_table('papers')
    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_methods_slug'))

    op.drop_table('methods')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_entity_type'))
        batch_op.drop_index(batch_op.f('ix_embeddings_entity_id'))
        batch_op.drop_index(batch_op.f('ix_embeddings_content_hash'))

    op.drop_table('embeddings')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_slug'))

    op.drop_table('datasets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_calls_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_calls_job_id'))
        batch_op.drop_index(batch_op.f('ix_agent_calls_input_hash'))

    op.drop_table('agent_calls')
    # ### end Alembic commands ###

